datasource: #注意这里不是spring:下的
  master:
    jdbcUrl: jdbc:mysql://localhost:3306/two_db_master?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
  slave:
    jdbcUrl: jdbc:mysql://localhost:3306/two_db_slave?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
spring:
  mvc:
    view:
      prefix: /
      suffix: .html
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/