server:
  port: 8001
spring:
  rabbitmq:
    username: zy
    password: 123456
    host: 192.168.0.156
    port: 5672
    connection-timeout: 15000
    publisher-confirms: true #confirm模式
    publisher-returns: true #return机制
    template:
      mandatory: true #与return机制结合配置次属性
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual #手工签收
        concurrency: 5
        max-concurrency: 10
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true